#%RAML 1.0
---
title: University Schedule API
baseUri: http://api.uni-schedule.com/{version}
version: v1


/groups:
    get:
        queryParameters:
            faculty:
                displayName: Faculty
                type: string
                description: a Faculty's name
                example: Faculty of Computers, Informatics and Microelectronics
                required: false
            specialty:
                displayName: Specialty
                type: string
                description: a Specialty's name
                example: Software Engineering
                required: false
            year:
                displayName: Year
                type: number
                description: the Year of studying the group is currently in
                example: 3
                required: false
    put:
    post:
    /{groupname}:
        get:
            description: Retrieve a specific Group name
            responses:
                200:
                    body:
                        application/json:
                            example: |
                                {
                                    "data": {
                                        "id": "SbBGk",
                                        "name": "FAF-171",
                                        "description": null,
                                        "faculty": "Faculty of Computers, Informatics and Microelectronics",
                                        "specialty": "Software Engineering",
                                        "link": "http://uni-schedule.com/groups/FAF-171"
                                    },
                                    "success": true,
                                    "status": 200
                                } 
        post:
        put:
            queryParameters:
                access_token:
                    displayName: Access Token
                    type: string
                    description: Token giving you permission to make call
                    required: true
        delete:
            queryParameters:
                access_token:
                    displayName: Access Token
                    type: string
                    description: Token giving you permission to make call
                    required: true

/classes:
    get:
/teachers:
    get: