#%RAML 1.0 ResourceType
  description: Collection of available <<resourcePathName>> in the API
  get:
    description: Get a list of <<resourcePathName>>.
    is: [returnsCollection]
  post:
    description: |
      Add a new <<resourcePathName|!singularize>> to the API.
    queryParameters:
      access_token:
        description: "The access token provided by the API"
        example: AABBCCDD
        required: true
        type: string
    body:
      application/json:
        type: <<resourcePathName|!singularize>>
    is: [returnsResourceCreatedMessage]
                            
