#%RAML 1.0 NamedExample
lesson1: # {key} - unique id
  lessonId: 01
  lessonName: "Internet of Things"
  faculty: "Faculty of Computers, Informatics and Microelectronics"
  specialty: "Software Engineering"
  year: 3
lesson2:
  lessonId: 02
  lessonName: "Data Structures and Algorithms"
  faculty: "Faculty of Computers, Informatics and Microelectronics"
  specialty: "Software Engineering"
  year: 1