#%RAML 1.0
---
title: University API
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/5c299ef9-4d1e-41bb-9d2b-d78af16932cb/{version} # baseUri: http://api.myUniversity.com/{version}
version: v1

types:
  group: !include groupType.raml
  lesson: !include lessonType.raml
  student: !include studentType.raml

resourceTypes:
  collection: !include collectionResource.raml
  collection-item: !include collectionItem.raml

traits: 
  returnsServerProblem:
    responses: 
      500:
        body: 
          application/json:
            example: |
              {"message":"Internal Server Error"}
  returnsResource:
    responses: 
      200:
        body: 
          application/json:
            type: <<resourcePathName|!singularize>>
  returnsResourceNotFound:
    responses:
      404:
        body:
          application/json:
            example: |
              {"message": "<<resourcePathName|!singularize>> not found" }
  returnsCollection:
    responses:
      200:
        body:
          application/json:
            type: <<resourcePathName|!singularize>>[]
  returnsResourceDeleted:
    responses:
      200:
        body:
          application/json:
            example: |
              {"message": "<<resourcePathName|!singularize>> successfully deleted" }
  returnsResourceCreated:
    responses:
      201:
        body:
          application/json:
            example: |
              {"message": "<<resourcePathName|!singularize>> successfully created!" }

/groups:
  type:
    collection:
  /{groupName}:
    type:
      collection-item:
    /lessons:
      type:
        collection:
      /{lessonId}:
        type:
          collection-item:
    /students:
      type:
        collection:
      /{studentId}:
        type:
          collection-item:



