#%RAML 1.0 NamedExample
student1: # {key} - unique id
  studentId: 10
  studentFullName: "Ion Cerempei"
  group: 
    groupId: 10
    groupName: "FAF-181"
    faculty: "Faculty of Computers, Informatics and Microelectronics"
    specialty: "Software Engineering"
